"""Theme color definitions for code-pretty-snap."""

THEMES = {
    # Dark themes
    "monokai": {
        "bg": "#272822",
        "fg": "#F8F8F2",
        "line_numbers": "#90908A",
        "highlight": "#3E3D32",
        "token_colors": {
            "Comment": "#75715E",
            "Keyword": "#F92672",
            "Name": "#F8F8F2",
            "Name.Function": "#A6E22E",
            "Name.Class": "#A6E22E",
            "Name.Decorator": "#A6E22E",
            "Name.Builtin": "#66D9EF",
            "Name.Attribute": "#A6E22E",
            "String": "#E6DB74",
            "Number": "#AE81FF",
            "Operator": "#F92672",
            "Punctuation": "#F8F8F2",
            "Comment.Special": "#FD971F",
            "Generic.Heading": "#F92672",
            "Generic.Subheading": "#A6E22E",
        },
        "window_bg": "#1D1E19",
        "title_color": "#F8F8F2",
        "tab_bg": "#1D1E19",
    },
    "dracula": {
        "bg": "#282A36",
        "fg": "#F8F8F2",
        "line_numbers": "#6272A4",
        "highlight": "#313345",
        "token_colors": {
            "Comment": "#6272A4",
            "Keyword": "#FF79C6",
            "Name": "#F8F8F2",
            "Name.Function": "#50FA7B",
            "Name.Class": "#50FA7B",
            "Name.Decorator": "#50FA7B",
            "Name.Builtin": "#8BE9FD",
            "Name.Attribute": "#50FA7B",
            "String": "#F1FA8C",
            "Number": "#BD93F9",
            "Operator": "#FF79C6",
            "Punctuation": "#F8F8F2",
            "Comment.Special": "#FFB86C",
            "Generic.Heading": "#FF79C6",
            "Generic.Subheading": "#50FA7B",
        },
        "window_bg": "#191A21",
        "title_color": "#F8F8F2",
        "tab_bg": "#191A21",
    },
    "nord": {
        "bg": "#2E3440",
        "fg": "#D8DEE9",
        "line_numbers": "#616E88",
        "highlight": "#3B4252",
        "token_colors": {
            "Comment": "#616E88",
            "Keyword": "#81A1C1",
            "Name": "#D8DEE9",
            "Name.Function": "#88C0D0",
            "Name.Class": "#8FBCBB",
            "Name.Decorator": "#88C0D0",
            "Name.Builtin": "#81A1C1",
            "Name.Attribute": "#8FBCBB",
            "String": "#A3BE8C",
            "Number": "#B48EAD",
            "Operator": "#81A1C1",
            "Punctuation": "#D8DEE9",
            "Comment.Special": "#D08770",
            "Generic.Heading": "#81A1C1",
            "Generic.Subheading": "#88C0D0",
        },
        "window_bg": "#242933",
        "title_color": "#D8DEE9",
        "tab_bg": "#242933",
    },
    # Light themes
    "github": {
        "bg": "#FFFFFF",
        "fg": "#24292E",
        "line_numbers": "#959DA5",
        "highlight": "#F6F8FA",
        "token_colors": {
            "Comment": "#6A737D",
            "Keyword": "#D73A49",
            "Name": "#24292E",
            "Name.Function": "#6F42C1",
            "Name.Class": "#6F42C1",
            "Name.Decorator": "#6F42C1",
            "Name.Builtin": "#005CC5",
            "Name.Attribute": "#6F42C1",
            "String": "#032F62",
            "Number": "#005CC5",
            "Operator": "#D73A49",
            "Punctuation": "#24292E",
            "Comment.Special": "#D73A49",
            "Generic.Heading": "#D73A49",
            "Generic.Subheading": "#6F42C1",
        },
        "window_bg": "#F6F8FA",
        "title_color": "#24292E",
        "tab_bg": "#F6F8FA",
    },
    "one-light": {
        "bg": "#FAFAFA",
        "fg": "#383A42",
        "line_numbers": "#9D9D9F",
        "highlight": "#F0F0F1",
        "token_colors": {
            "Comment": "#A0A1A7",
            "Keyword": "#A626A4",
            "Name": "#383A42",
            "Name.Function": "#4078F2",
            "Name.Class": "#4078F2",
            "Name.Decorator": "#4078F2",
            "Name.Builtin": "#4078F2",
            "Name.Attribute": "#E45649",
            "String": "#50A14F",
            "Number": "#986801",
            "Operator": "#A626A4",
            "Punctuation": "#383A42",
            "Comment.Special": "#A626A4",
            "Generic.Heading": "#A626A4",
            "Generic.Subheading": "#4078F2",
        },
        "window_bg": "#F0F0F1",
        "title_color": "#383A42",
        "tab_bg": "#F0F0F1",
    },
    "solarized-light": {
        "bg": "#FDF6E3",
        "fg": "#657B83",
        "line_numbers": "#93A1A1",
        "highlight": "#EEE8D5",
        "token_colors": {
            "Comment": "#93A1A1",
            "Keyword": "#859900",
            "Name": "#657B83",
            "Name.Function": "#268BD2",
            "Name.Class": "#268BD2",
            "Name.Decorator": "#268BD2",
            "Name.Builtin": "#859900",
            "Name.Attribute": "#B58900",
            "String": "#2AA198",
            "Number": "#D33682",
            "Operator": "#859900",
            "Punctuation": "#657B83",
            "Comment.Special": "#CB4B16",
            "Generic.Heading": "#859900",
            "Generic.Subheading": "#268BD2",
        },
        "window_bg": "#EEE8D5",
        "title_color": "#657B83",
        "tab_bg": "#EEE8D5",
    },
}

THEME_NAMES = list(THEMES.keys())


def get_theme(name: str) -> dict:
    """Get a theme dict by name. Raises KeyError if not found."""
    if name not in THEMES:
        raise KeyError(
            f"Unknown theme '{name}'. Available themes: {', '.join(THEME_NAMES)}"
        )
    return THEMES[name]
